import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import Image from 'next/image'
import Nexos from '../public/nexos.svg' 
const geits = Bebas_Neue({
  subsets: ['latin'],
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${geits.className}  antialiased`}>

  
        {children}
      </body>
    </html>
  );
}
